name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Publish
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.15]
        java: [zulu@1.17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cleanup Ref
        id: ref
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: 'refs\/\w+\/(.*)'
          string: ${{ github.ref }}
          replace-with: '$1'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Remove Cached Harana Artefacts
        run: |
          rm -fr ~/.cache/coursier/v1/https/maven.pkg.github.com

      - name: Publish Packages
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES_TOKEN }}
        run: sbt ++${{ matrix.scala }} publish

      - name: Get Scala Major Version
        id: scala
        uses: actions-ecosystem/action-regex-match@v2
        with:
          regex: '([0-9]+\.[0-9]+)\.[0-9]+'
          text: ${{ matrix.scala }}

      - name: Remove Older Snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.2.0
        with:
          keep: 2
          version-pattern: ".+?SNAPSHOT"
          names: |
            com.harana.sdk_${{ steps.scala.outputs.group1 }}
            com.harana.sdkJS_${{ steps.scala.outputs.group1 }}

      - name: Remove Older Releases
        uses: smartsquaregmbh/delete-old-packages@v0.2.0
        with:
          keep: 2
          version-pattern: .*[^SNAPSHOT]$
          names: |
            com.harana.sdk_${{ steps.scala.outputs.group1 }}
            com.harana.sdkJS_${{ steps.scala.outputs.group1 }}

      - name: Notify Slack - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_FOOTER: ""
          SLACK_MESSAGE: "✅  sdk  |  publish  |  ${{ steps.ref.outputs.replaced }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_BUILDS_WEBHOOK }}

      - name: Notify Slack - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_FOOTER: ""
          SLACK_MESSAGE: "⛔️  sdk  |  publish  |  ${{ steps.ref.outputs.replaced }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_BUILDS_WEBHOOK }}